# Generated by Django 5.1.7 on 2025-03-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
