# Generated by Django 5.1.7 on 2025-03-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
